spring:
  flyway:
    enabled: true
    baseline-on-migrate: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    username: postgres
    password: mullen2906
    url: jdbc:postgresql://localhost:5432/taskhive
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt.public.key: classpath:app.pub
jwt.private.key: classpath:app.key